name: Test

on: [push]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo 'hello there!'
  util-tests:
    needs: greeting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and clone
        uses: actions/checkout@v4.1.1
      - name: Install dependencies
        run: npm ci
      - name: test utils
        run: npm run test utils.test
  app-tests:
    needs: util-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and clone
        uses: actions/checkout@v4.1.1

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2

      - name: Install dependencies
        run: npm ci

      - name: Setup PostgreSQL
        uses: Harmon758/postgresql-action@v1.0.0

        with:
          username: ci
          password: password
          database: test
          port: 5432
          id: postgres

      - name: psql start
        run: sudo service postgresql start

      - name: create db
        run: psql -f ./db/setup.sql

      - name: run tests
        run: npm run test app.test
