name: Test

on: [push]
jobs:
  util-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and clone
        uses: actions/checkout@v4.1.1
      - name: Install dependencies
        run: npm ci
      - name: test utils
        run: npm run test utils.test
  app-tests:
    needs: util-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and clone
        uses: actions/checkout@v4.1.1

      - name: Use Node.js
        uses: actions/setup-node@v4.0.2

      - name: Setup PostgreSQL
        uses: Harmon758/postgresql-action@v1
        with:
          postgresql db: "nc_news_test"
          postgresql user: "test_user"
          postgresql password: "test_password"

      - name: Install dependencies
        run: npm ci

      - name: test
        run: PGDATABASE=nc_news_test PGUSER=test_user PGPASSWORD=test_password npm test

  deploy:
    needs: app-tests
    if: github.ref == 'refs/heads/main'
    runs-on: ubunto latest
    steps:
      - name: Deploy to Render
        run: curl ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
